-- Cambridge IELTS 21 Academic Listening Test 2
INSERT INTO tests (id, title, description, level, duration_minutes, is_active) VALUES
(2102, 'Cambridge IELTS 21 Academic Listening Test 2', 'Rasmiy Cambridge IELTS 21 to''plamidan olingan to''liq 4 ta qism va 40 ta savoldan iborat akademik Listening imtihoni.', 'Multi-level (A1-C1)', 30, true)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, is_active = true;

INSERT INTO sections (id, test_id, type, title, instructions, audio_url, passage_text, order_index) VALUES
(21021, 2102, 'listening', 'Listening Part 1', '<div class="ielts-reading-container">
<h2 class="ielts-reading-question-section-heading">
                                            Questions 1-10                                                                                                                                                                                                    
                                                                                                                                    </h2>
                                                                                <div class="ielts-reading-question-section-content">
                                            <p>Complete the table below.</p>
<p>Write ONE WORD AND/OR A NUMBER for each answer.</p>
<table>
<tbody>
<tr>
<td>Course</td>
<td>Date</td>
<td>Cost</td>
<td>Notes</td>
</tr>
<tr>
<td>Vietnamese food</td>
<td><span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">1</strong><input type="text" data-qnum="1" name="question_1" class="ielts-inline-input" placeholder="[1] javob..." autocomplete="off" spellcheck="false"></span></span></td>
<td>£59</td>
<td>It provides information on the use of herbs.</p>
<p>There are no places at present.</td>
</tr>
<tr>
<td>Bread making</td>
<td>20 March</td>
<td>£ <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">2</strong><input type="text" data-qnum="2" name="question_2" class="ielts-inline-input" placeholder="[2] javob..." autocomplete="off" spellcheck="false"></span></span></td>
<td>There is also an extra charge for ingredients.</p>
<p>Participants make white bread, sourdough and <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">3</strong><input type="text" data-qnum="3" name="question_3" class="ielts-inline-input" placeholder="[3] javob..." autocomplete="off" spellcheck="false"></span></span>.</td>
</tr>
<tr>
<td>Face massage</td>
<td>23 February</td>
<td>£35</td>
<td>The teacher trained in <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">4</strong><input type="text" data-qnum="4" name="question_4" class="ielts-inline-input" placeholder="[4] javob..." autocomplete="off" spellcheck="false"></span></span>.</p>
<p>Bring a <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">5</strong><input type="text" data-qnum="5" name="question_5" class="ielts-inline-input" placeholder="[5] javob..." autocomplete="off" spellcheck="false"></span></span>.</td>
</tr>
<tr>
<td>Candle making</td>
<td><span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">6</strong><input type="text" data-qnum="6" name="question_6" class="ielts-inline-input" placeholder="[6] javob..." autocomplete="off" spellcheck="false"></span></span></td>
<td>£52</td>
<td>Only <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">7</strong><input type="text" data-qnum="7" name="question_7" class="ielts-inline-input" placeholder="[7] javob..." autocomplete="off" spellcheck="false"></span></span> ingredients are used.</p>
<p>The candles can be used as presents.</td>
</tr>
<tr>
<td>Silk painting</td>
<td>18 May</td>
<td>£ <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">8</strong><input type="text" data-qnum="8" name="question_8" class="ielts-inline-input" placeholder="[8] javob..." autocomplete="off" spellcheck="false"></span></span></td>
<td>Bring an apron or old <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">9</strong><input type="text" data-qnum="9" name="question_9" class="ielts-inline-input" placeholder="[9] javob..." autocomplete="off" spellcheck="false"></span></span>.</td>
</tr>
<tr>
<td>DIY for beginners</td>
<td>24 February</td>
<td>£125</td>
<td>Learn how to</p>
<p>• use a drill, saw and <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">10</strong><input type="text" data-qnum="10" name="question_10" class="ielts-inline-input" placeholder="[10] javob..." autocomplete="off" spellcheck="false"></span></span></p>
<p>• put up a shelf.</td>
</tr>
</tbody>
</table>
                                        </div>
                                        <div class="ielts-reading-questions">
                                                                                                                                                                                            </div>
                                        </div>
</div>', 'https://ielts-listening-audio.engnovatemedia.com/3178718-cambridge-ielts-21-academic-listening-test-2-1.mp3', 'MAN: Hello, Steynford College external course registration, can I help you?
WOMAN: Yeah, I''m ringing to find out about one-day classes next year. I got a leaflet about them in the post but I lost it, and I understand some of the classes are filling up fast, so I might need to book quite soon if I want to go ahead.
MAN: Sure. Can you remember which one you were considering?
WOMAN: There were a few actually. I remember there was one on how to make Vietnamese food that sounded good. I think that was on the 13th of January. It cost about 60 pounds.
MAN: Yes, you''re right about the date, but it''s 59 pounds actually. It''s a very popular class, and among other things the teacher explains how Vietnamese food includes lots of different herbs. I''m afraid that all the places are taken at present, but I can put you on the waiting list if you want?
WOMAN: No, that''s OK. I''m quite interested in the bread making class. That''s in March sometime, isn''t it?
MAN: Yeah, the 20th of March. Would you like to register for that?
WOMAN: I''m not sure. How much is it?
MAN: The actual cost is £48 but then there''s an extra charge as well as that for the ingredients - I''m not sure how much that is, no more than twenty pounds I think.
WOMAN: So what sorts of things do they make in the class?
MAN: Oh, various types of bread; I think they make white bread and then they make sourdough, that seems to be very fashionable at present, and they learn how to make pizza, which is apparently really good.
WOMAN: Well I''d definitely be interested in that, but there were also a few other classes that sounded interesting. I think there was one on face massage? I''d love to learn how to do that.
MAN: Yeah, that''s on the 23rd of February and it costs just £35 for the day. The teacher''s great, the type of massage done is a traditional technique used in India and she actually did her training there. The massage is meant to relax you and get rid of lines and wrinkles. You practise it on yourself so you have to take a mirror to the class, so you can see what you''re doing.
WOMAN: OK.
WOMAN: And I think there was a class in candle making?
MAN: Yes that''s sometime in April, I think. Let me check ... yes, it''s on the 6th. It was on the 23rd of January but they had to change the date. It''s just £52. That''s a popular course too. I think one reason why people like it is because the candles are all made out of natural products. It''s filling up fast but there''s still a few places left.
WOMAN: Yes one of my friends did that class. She said the candles make really good presents. In fact she gave me one.
MAN: By the way, have you heard about the class on silk painting? That''s being held on the 18th of May. You learn how to create designs on silk fabric and colour them using special dyes. Apparently people can produce beautiful artworks that way, either to put on the wall as a picture or to use for something like a scarf. It''s £67.50, which is really good value I think - there''s a similar class I''ve seen that was £110.
WOMAN: That sounds interesting. Would I need to bring the silk?
MAN: No, the only thing is everyone has to bring something to protect their clothing, like an apron if you''ve got one, or a shirt that you don''t use any more, because the dye can really stain your clothes.
WOMAN: Right. Then the last class I was considering was a bit different, that was on DIY for beginners. I''d like to learn how to do household repairs. Are there any places left on that?
MAN: That''s on the 24th of February - yes, there are a few places. It''s a bit more expensive - it''s £125 - but it''s a very popular class. You learn how to use an electric drill and a saw.
WOMAN: Yeah, that would be really useful, and I even need to learn how to use a hammer because I always end up hitting my fingers.
MAN: Yes, you''ll do that too. And when you''ve learned how to use the basic tools, you do a practical job which is fixing a shelf to a wall.
WOMAN: Great. Just what I need to know. Right, well I''d like to enrol for that and also for ...', 1)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, instructions = EXCLUDED.instructions, audio_url = EXCLUDED.audio_url, passage_text = EXCLUDED.passage_text;

INSERT INTO questions (id, section_id, question_type, question_text, options, correct_answer, points, order_index) VALUES
(210201, 21021, 'text_input', 'Course 
 Date 
 Cost 
 Notes 
 
 
 Vietnamese food 
  <strong', '[]'::jsonb, '13th January / 13 January / January 13 / January 13th / 13.01 / 13.1', 1, 1),
(210202, 21021, 'text_input', 'Bread making 
 20 March 
 £  <strong', '[]'::jsonb, '48', 1, 2),
(210203, 21021, 'text_input', 'Participants make white bread, sourdough and  <strong', '[]'::jsonb, 'pizza', 1, 3),
(210204, 21021, 'text_input', 'Face massage 
 23 February 
 £35 
 The teacher trained in  <strong', '[]'::jsonb, 'India', 1, 4),
(210205, 21021, 'text_input', 'Bring a  <strong', '[]'::jsonb, 'mirror', 1, 5),
(210206, 21021, 'text_input', 'Candle making 
  <strong', '[]'::jsonb, '6th April / 6 April / April 6 / April 6th / 06.04 / 6.4', 1, 6),
(210207, 21021, 'text_input', 'g-question-item"> 6     
 £52 
 Only  <strong', '[]'::jsonb, 'natural', 1, 7),
(210208, 21021, 'text_input', 'Silk painting 
 18 May 
 £  <strong', '[]'::jsonb, '67.50', 1, 8),
(210209, 21021, 'text_input', 'estion-item"> 8     
 Bring an apron or old  <strong', '[]'::jsonb, 'shirt', 1, 9),
(210210, 21021, 'text_input', 'DIY for beginners 
 24 February 
 £125 
 Learn how to 
 • use a drill, saw and  <strong', '[]'::jsonb, 'hammer', 1, 10)
ON CONFLICT (id) DO UPDATE SET question_text = EXCLUDED.question_text, options = EXCLUDED.options, correct_answer = EXCLUDED.correct_answer, points = EXCLUDED.points;

INSERT INTO sections (id, test_id, type, title, instructions, audio_url, passage_text, order_index) VALUES
(21022, 2102, 'listening', 'Listening Part 2', '<div class="ielts-reading-container">
<h2 class="ielts-reading-question-section-heading">
                                            Questions 11-12                                                                                                                                                
                                                                                                                                    </h2>
                                                                                <div class="ielts-reading-question-section-content">
                                            <p>Choose TWO letters, A-E.</p>
                                        </div>
                                        <div class="ielts-reading-questions">
                                                                                                                                                                                            <div class="ielts-standalone-q ielts-multi-q" data-multi-qnums="11,12"><div class="ielts-q-header"><strong class="ielts-q-badge">11</strong> <strong class="ielts-q-badge">12</strong><span class="ielts-q-title">Which TWO pieces of advice are given about the Marsden Coastal Walk?</span></div><div class="ielts-checkbox-group"><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="11,12" data-limit="2" value="A"><span class="ielts-radio-text"><strong>A</strong> Stop for lunch in an ancient town.</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="11,12" data-limit="2" value="B"><span class="ielts-radio-text"><strong>B</strong> Don''t miss the ruins of a certain building.</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="11,12" data-limit="2" value="C"><span class="ielts-radio-text"><strong>C</strong> Catch a boat to the start of this walk.</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="11,12" data-limit="2" value="D"><span class="ielts-radio-text"><strong>D</strong> Be careful of the steep and rocky paths.</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="11,12" data-limit="2" value="E"><span class="ielts-radio-text"><strong>E</strong> Don''t worry about getting lost.</span></label></div></div></div>
                                                                                                                                    </div>
                                                                                                                                                            <h2 class="ielts-reading-question-section-heading">
                                            Questions 13-14                                                                                                                                                
                                                                                                                                    </h2>
                                                                                <div class="ielts-reading-question-section-content">
                                            <p>Choose TWO letters, A-E.</p>
                                        </div>
                                        <div class="ielts-reading-questions">
                                                                                                                                                                                            <div class="ielts-standalone-q ielts-multi-q" data-multi-qnums="13,14"><div class="ielts-q-header"><strong class="ielts-q-badge">13</strong> <strong class="ielts-q-badge">14</strong><span class="ielts-q-title">Which TWO things are said about the Melby Heritage Walk?</span></div><div class="ielts-checkbox-group"><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="13,14" data-limit="2" value="A"><span class="ielts-radio-text"><strong>A</strong> This walk is mostly downhill.</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="13,14" data-limit="2" value="B"><span class="ielts-radio-text"><strong>B</strong> The paths can get busy during the day.</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="13,14" data-limit="2" value="C"><span class="ielts-radio-text"><strong>C</strong> This is a circular walk.</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="13,14" data-limit="2" value="D"><span class="ielts-radio-text"><strong>D</strong> A tower stands on the site of an older structure.</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="13,14" data-limit="2" value="E"><span class="ielts-radio-text"><strong>E</strong> There are far-reaching views the whole way.</span></label></div></div></div>
                                                                                                                                    </div>
                                                                                                                                                            <h2 class="ielts-reading-question-section-heading">
                                            Questions 15-20                                                                                                                                                
                                                                                                                                    </h2>
                                                                                <div class="ielts-reading-question-section-content">
                                            <p>Label the map below.</p>
<p>Write the correct letter, A-I, next to Questions 15-20.</p>
<p><img src="https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-2-4-diagram-6a3cf580846f3.jpg" alt="" /></p>
                                        </div>
                                        <div class="ielts-reading-questions">
                                                                                                                                                                                                <table class="ielts-listening-matching-table"><thead><tr><th></th><th>A</th><th>B</th><th>C</th><th>D</th><th>E</th><th>F</th><th>G</th><th>H</th><th>I</th></tr></thead><tbody><tr class="ielts-listening-question-item"><td class="ielts-listening-matching-question-cell"><strong id="ielts-listening-question-number-15" class="ielts-q-badge">15</strong> Exhibition</td>
                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="15" type="radio" name="question_15" id="ielts_listening_answer_3178422_1_0" value="A"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="15" type="radio" name="question_15" id="ielts_listening_answer_3178422_1_1" value="B"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="15" type="radio" name="question_15" id="ielts_listening_answer_3178422_1_2" value="C"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="15" type="radio" name="question_15" id="ielts_listening_answer_3178422_1_3" value="D"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="15" type="radio" name="question_15" id="ielts_listening_answer_3178422_1_4" value="E"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="15" type="radio" name="question_15" id="ielts_listening_answer_3178422_1_5" value="F"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="15" type="radio" name="question_15" id="ielts_listening_answer_3178422_1_6" value="G"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="15" type="radio" name="question_15" id="ielts_listening_answer_3178422_1_7" value="H"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="15" type="radio" name="question_15" id="ielts_listening_answer_3178422_1_8" value="I"></td></tr>                                                                                                                                                                                                                                                                                                    <tr class="ielts-listening-question-item"><td class="ielts-listening-matching-question-cell"><strong id="ielts-listening-question-number-16" class="ielts-q-badge">16</strong> Baths</td>
                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="16" type="radio" name="question_16" id="ielts_listening_answer_3178422_2_0" value="A"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="16" type="radio" name="question_16" id="ielts_listening_answer_3178422_2_1" value="B"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="16" type="radio" name="question_16" id="ielts_listening_answer_3178422_2_2" value="C"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="16" type="radio" name="question_16" id="ielts_listening_answer_3178422_2_3" value="D"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="16" type="radio" name="question_16" id="ielts_listening_answer_3178422_2_4" value="E"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="16" type="radio" name="question_16" id="ielts_listening_answer_3178422_2_5" value="F"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="16" type="radio" name="question_16" id="ielts_listening_answer_3178422_2_6" value="G"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="16" type="radio" name="question_16" id="ielts_listening_answer_3178422_2_7" value="H"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="16" type="radio" name="question_16" id="ielts_listening_answer_3178422_2_8" value="I"></td></tr>                                                                                                                                                                                                                                                                                                    <tr class="ielts-listening-question-item"><td class="ielts-listening-matching-question-cell"><strong id="ielts-listening-question-number-17" class="ielts-q-badge">17</strong> Tools</td>
                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="17" type="radio" name="question_17" id="ielts_listening_answer_3178422_3_0" value="A"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="17" type="radio" name="question_17" id="ielts_listening_answer_3178422_3_1" value="B"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="17" type="radio" name="question_17" id="ielts_listening_answer_3178422_3_2" value="C"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="17" type="radio" name="question_17" id="ielts_listening_answer_3178422_3_3" value="D"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="17" type="radio" name="question_17" id="ielts_listening_answer_3178422_3_4" value="E"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="17" type="radio" name="question_17" id="ielts_listening_answer_3178422_3_5" value="F"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="17" type="radio" name="question_17" id="ielts_listening_answer_3178422_3_6" value="G"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="17" type="radio" name="question_17" id="ielts_listening_answer_3178422_3_7" value="H"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="17" type="radio" name="question_17" id="ielts_listening_answer_3178422_3_8" value="I"></td></tr>                                                                                                                                                                                                                                                                                                    <tr class="ielts-listening-question-item"><td class="ielts-listening-matching-question-cell"><strong id="ielts-listening-question-number-18" class="ielts-q-badge">18</strong> Vehicles</td>
                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="18" type="radio" name="question_18" id="ielts_listening_answer_3178422_4_0" value="A"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="18" type="radio" name="question_18" id="ielts_listening_answer_3178422_4_1" value="B"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="18" type="radio" name="question_18" id="ielts_listening_answer_3178422_4_2" value="C"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="18" type="radio" name="question_18" id="ielts_listening_answer_3178422_4_3" value="D"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="18" type="radio" name="question_18" id="ielts_listening_answer_3178422_4_4" value="E"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="18" type="radio" name="question_18" id="ielts_listening_answer_3178422_4_5" value="F"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="18" type="radio" name="question_18" id="ielts_listening_answer_3178422_4_6" value="G"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="18" type="radio" name="question_18" id="ielts_listening_answer_3178422_4_7" value="H"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="18" type="radio" name="question_18" id="ielts_listening_answer_3178422_4_8" value="I"></td></tr>                                                                                                                                                                                                                                                                                                    <tr class="ielts-listening-question-item"><td class="ielts-listening-matching-question-cell"><strong id="ielts-listening-question-number-19" class="ielts-q-badge">19</strong> Ponies</td>
                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="19" type="radio" name="question_19" id="ielts_listening_answer_3178422_5_0" value="A"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="19" type="radio" name="question_19" id="ielts_listening_answer_3178422_5_1" value="B"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="19" type="radio" name="question_19" id="ielts_listening_answer_3178422_5_2" value="C"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="19" type="radio" name="question_19" id="ielts_listening_answer_3178422_5_3" value="D"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="19" type="radio" name="question_19" id="ielts_listening_answer_3178422_5_4" value="E"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="19" type="radio" name="question_19" id="ielts_listening_answer_3178422_5_5" value="F"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="19" type="radio" name="question_19" id="ielts_listening_answer_3178422_5_6" value="G"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="19" type="radio" name="question_19" id="ielts_listening_answer_3178422_5_7" value="H"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="19" type="radio" name="question_19" id="ielts_listening_answer_3178422_5_8" value="I"></td></tr>                                                                                                                                                                                                                                                                                                    <tr class="ielts-listening-question-item"><td class="ielts-listening-matching-question-cell"><strong id="ielts-listening-question-number-20" class="ielts-q-badge">20</strong> Education centre</td>
                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="20" type="radio" name="question_20" id="ielts_listening_answer_3178422_6_0" value="A"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="20" type="radio" name="question_20" id="ielts_listening_answer_3178422_6_1" value="B"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="20" type="radio" name="question_20" id="ielts_listening_answer_3178422_6_2" value="C"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="20" type="radio" name="question_20" id="ielts_listening_answer_3178422_6_3" value="D"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="20" type="radio" name="question_20" id="ielts_listening_answer_3178422_6_4" value="E"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="20" type="radio" name="question_20" id="ielts_listening_answer_3178422_6_5" value="F"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="20" type="radio" name="question_20" id="ielts_listening_answer_3178422_6_6" value="G"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="20" type="radio" name="question_20" id="ielts_listening_answer_3178422_6_7" value="H"></td>                                                                                                            <td class="ielts-listening-matching-option-cell"><input data-qnum="20" type="radio" name="question_20" id="ielts_listening_answer_3178422_6_8" value="I"></td></tr></tbody></table>                                                                                                                                                                                        </div>
                                        </div>
</div>', 'https://ielts-listening-audio.engnovatemedia.com/3178717-cambridge-ielts-21-academic-listening-test-2-2.mp3', 'Here is some information about history and nature walks in the region. They can be completed in less than a day and also be combined with a visit to Melby, a former coal mine now open to the public.
The Marsden Coastal Walk is suitable for all the family as there are no strenuous climbs. The route begins at Marsden harbour, where there are hourly ferries to and from the beautiful Hooker Island, a great place for fishing. The walk covers part of the coastal path trail. As there are clear signposts all along the way, you don''t even need to take a map with you. At one point, the route goes inland slightly and passes a castle built in the 1400s near to a now-vanished market town. The castle''s now just a pile of stones but it''s a great place to take photos, and fascinating information boards show what it once looked like. If you set off early, you can be back in time for midday.
The Melby Heritage Walk is a great place to take photos, especially of the night sky. At certain times of the year, people come here from far and wide. They climb to the top of the valley and take pictures of the stars. In the daytime, it''s completely different. As you hike through the dense woods in the valley bottom, the only things you''ll hear are the sound of your own footsteps. At the highest point, you can stop to take in the views, and those with lots of energy can climb the tower that''s situated where there was once a seventeenth century hunting lodge. The route continues along the tops of the hills and brings you back down to the starting point - the car park at Melby Coal Mine.
Melby Coal Mine has been open to the public for twenty years and has won awards for its visitor experience. Many of the buildings around the mine are still standing and have been converted into display areas.
Firstly, there''s an exhibition showing the history of the mine, with many original black and white photos. To see that, you go from the car park, via a covered walkway to the Main Visitor Centre. Go through the ticket office to an area where there are lockers to leave heavy bags in, and where you can borrow raincoats. Beyond that room is the exhibition.
There''s a small bathhouse where miners used to wash after their shift underground. You can see that in the building directly to the north of the engine house. The boiler has gone from there now, but there are lines of tin baths on the stone floor.
There''s a display of early mining tools from the days before mechanisation. You can find that in a small L-shaped building in the middle of the northern boundary of the site. It''s incredible to think how miners were able to use hand implements to cut through rock.
The vehicle shed, where you can find wagons of different sizes, along with some of the hi-tech cutting machines that were in use until the mine closed, is in the southwest corner of the site, and can be accessed via a covered walkway.
There is a field with ponies, which are always popular with children, on the north-eastern boundary of the site, not approached via a covered walkway.
The other building to mention is the education centre. This is where school groups go when they visit the mine, but it''s also accessible to the public as it contains a library and small gift shop. The centre is connected to the ticket office via a short section of covered walkway.', 2)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, instructions = EXCLUDED.instructions, audio_url = EXCLUDED.audio_url, passage_text = EXCLUDED.passage_text;

INSERT INTO questions (id, section_id, question_type, question_text, options, correct_answer, points, order_index) VALUES
(210211, 21022, 'multiple_choice', 'Question 11', '["A", "B", "C", "D", "E"]'::jsonb, 'B / E', 1, 11),
(210212, 21022, 'multiple_choice', 'Question 12', '["A", "B", "C", "D", "E"]'::jsonb, 'B / E', 1, 12),
(210213, 21022, 'multiple_choice', 'Question 13', '["A", "B", "C", "D", "E"]'::jsonb, 'C / D', 1, 13),
(210214, 21022, 'multiple_choice', 'Question 14', '["A", "B", "C", "D", "E"]'::jsonb, 'C / D', 1, 14),
(210215, 21022, 'multiple_choice', 'Question 15', '["A", "B", "C", "D", "E", "F", "G", "H", "I"]'::jsonb, 'F', 1, 15),
(210216, 21022, 'multiple_choice', 'Question 16', '["A", "B", "C", "D", "E", "F", "G", "H", "I"]'::jsonb, 'B', 1, 16),
(210217, 21022, 'multiple_choice', 'Question 17', '["A", "B", "C", "D", "E", "F", "G", "H", "I"]'::jsonb, 'D', 1, 17),
(210218, 21022, 'multiple_choice', 'Question 18', '["A", "B", "C", "D", "E", "F", "G", "H", "I"]'::jsonb, 'A', 1, 18),
(210219, 21022, 'multiple_choice', 'Question 19', '["A", "B", "C", "D", "E", "F", "G", "H", "I"]'::jsonb, 'H', 1, 19),
(210220, 21022, 'multiple_choice', 'Question 20', '["A", "B", "C", "D", "E", "F", "G", "H", "I"]'::jsonb, 'E', 1, 20)
ON CONFLICT (id) DO UPDATE SET question_text = EXCLUDED.question_text, options = EXCLUDED.options, correct_answer = EXCLUDED.correct_answer, points = EXCLUDED.points;

INSERT INTO sections (id, test_id, type, title, instructions, audio_url, passage_text, order_index) VALUES
(21023, 2102, 'listening', 'Listening Part 3', '<div class="ielts-reading-container">
<h2 class="ielts-reading-question-section-heading">
                                            Questions 21-22                                                                                                                                                
                                                                                                                                    </h2>
                                                                                <div class="ielts-reading-question-section-content">
                                            <p>Choose TWO letters, A-E.</p>
                                        </div>
                                        <div class="ielts-reading-questions">
                                                                                                                                                                                            <div class="ielts-standalone-q ielts-multi-q" data-multi-qnums="21,22"><div class="ielts-q-header"><strong class="ielts-q-badge">21</strong> <strong class="ielts-q-badge">22</strong><span class="ielts-q-title">Which TWO facts in the sessions on food safety were new information for Nadia and Fergus?</span></div><div class="ielts-checkbox-group"><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="21,22" data-limit="2" value="A"><span class="ielts-radio-text"><strong>A</strong> the amount of plastic in the ocean</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="21,22" data-limit="2" value="B"><span class="ielts-radio-text"><strong>B</strong> the number of diseases caused by contaminated food</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="21,22" data-limit="2" value="C"><span class="ielts-radio-text"><strong>C</strong> the amount of food that is wasted</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="21,22" data-limit="2" value="D"><span class="ielts-radio-text"><strong>D</strong> the number of people who are obese</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="21,22" data-limit="2" value="E"><span class="ielts-radio-text"><strong>E</strong> the result of treating animals with antibiotics</span></label></div></div></div>
                                                                                                                                    </div>
                                                                                                                                                            <h2 class="ielts-reading-question-section-heading">
                                            Questions 23-24                                                                                                                                                
                                                                                                                                    </h2>
                                                                                <div class="ielts-reading-question-section-content">
                                            <p>Choose TWO letters, A-E.</p>
                                        </div>
                                        <div class="ielts-reading-questions">
                                                                                                                                                                                            <div class="ielts-standalone-q ielts-multi-q" data-multi-qnums="23,24"><div class="ielts-q-header"><strong class="ielts-q-badge">23</strong> <strong class="ielts-q-badge">24</strong><span class="ielts-q-title">Which TWO features of a project aiming to prevent food fraud impressed Fergus?</span></div><div class="ielts-checkbox-group"><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="23,24" data-limit="2" value="A"><span class="ielts-radio-text"><strong>A</strong> the new technology it used</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="23,24" data-limit="2" value="B"><span class="ielts-radio-text"><strong>B</strong> the publicity it received</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="23,24" data-limit="2" value="C"><span class="ielts-radio-text"><strong>C</strong> the use of multiple tests on food items</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="23,24" data-limit="2" value="D"><span class="ielts-radio-text"><strong>D</strong> the variety of dietary requirements included</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="23,24" data-limit="2" value="E"><span class="ielts-radio-text"><strong>E</strong> the way information was made widely accessible</span></label></div></div></div>
                                                                                                                                    </div>
                                                                                                                                                            <h2 class="ielts-reading-question-section-heading">
                                            Questions 25-26                                                                                                                                                
                                                                                                                                    </h2>
                                                                                <div class="ielts-reading-question-section-content">
                                            <p>Choose TWO letters, A-E.</p>
                                        </div>
                                        <div class="ielts-reading-questions">
                                                                                                                                                                                            <div class="ielts-standalone-q ielts-multi-q" data-multi-qnums="25,26"><div class="ielts-q-header"><strong class="ielts-q-badge">25</strong> <strong class="ielts-q-badge">26</strong><span class="ielts-q-title">Which TWO topics do both students recommend should be included in the course?</span></div><div class="ielts-checkbox-group"><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="25,26" data-limit="2" value="A"><span class="ielts-radio-text"><strong>A</strong> sustainable fishing</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="25,26" data-limit="2" value="B"><span class="ielts-radio-text"><strong>B</strong> targeted nutrition</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="25,26" data-limit="2" value="C"><span class="ielts-radio-text"><strong>C</strong> global differences in consumption</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="25,26" data-limit="2" value="D"><span class="ielts-radio-text"><strong>D</strong> sustainable agriculture</span></label><label class="ielts-checkbox-btn"><input type="checkbox" data-multi-qnums="25,26" data-limit="2" value="E"><span class="ielts-radio-text"><strong>E</strong> digital technology and food</span></label></div></div></div>
                                                                                                                                    </div>
                                                                                                                                                            <h2 class="ielts-reading-question-section-heading">
                                            Questions 27-30                                                                                                                                                
                                                                                                                                    </h2>
                                                                                <div class="ielts-reading-question-section-content">
                                            <div class="ielts-listening-section-content-wrapper"><p>Complete the flow-chart below.</p>
<p>Choose FOUR answers from the box and write the correct letter, A-F, next to Questions 27-30.</p>
<p>Student project: developing a new food product</p>
<p>Initial aim</p>
<p><span class="ielts-listening-question-item"><span class="ielts-inline-select-wrap"><strong class="ielts-q-badge">27</strong><select data-qnum="27" name="question_27" class="ielts-inline-select"><option value="">[ 27 ] Tanlang...</option><option value="A. This was challenging but enjoyable.">A. This was challenging but enjoyable.</option><option value="B. This led to some disagreement.">B. This led to some disagreement.</option><option value="C. This was easy to decide on.">C. This was easy to decide on.</option><option value="D. This was helped by the guidelines provided.">D. This was helped by the guidelines provided.</option><option value="E. This seemed like an unnecessary stage.">E. This seemed like an unnecessary stage.</option><option value="F. This involved selecting a new ingredient.">F. This involved selecting a new ingredient.</option></select></span></span></p>
<p>Literature review</p>
<p><span class="ielts-listening-question-item"><span class="ielts-inline-select-wrap"><strong class="ielts-q-badge">28</strong><select data-qnum="28" name="question_28" class="ielts-inline-select"><option value="">[ 28 ] Tanlang...</option><option value="A. This was challenging but enjoyable.">A. This was challenging but enjoyable.</option><option value="B. This led to some disagreement.">B. This led to some disagreement.</option><option value="C. This was easy to decide on.">C. This was easy to decide on.</option><option value="D. This was helped by the guidelines provided.">D. This was helped by the guidelines provided.</option><option value="E. This seemed like an unnecessary stage.">E. This seemed like an unnecessary stage.</option><option value="F. This involved selecting a new ingredient.">F. This involved selecting a new ingredient.</option></select></span></span></p>
<p>Product development</p>
<p><span class="ielts-listening-question-item"><span class="ielts-inline-select-wrap"><strong class="ielts-q-badge">29</strong><select data-qnum="29" name="question_29" class="ielts-inline-select"><option value="">[ 29 ] Tanlang...</option><option value="A. This was challenging but enjoyable.">A. This was challenging but enjoyable.</option><option value="B. This led to some disagreement.">B. This led to some disagreement.</option><option value="C. This was easy to decide on.">C. This was easy to decide on.</option><option value="D. This was helped by the guidelines provided.">D. This was helped by the guidelines provided.</option><option value="E. This seemed like an unnecessary stage.">E. This seemed like an unnecessary stage.</option><option value="F. This involved selecting a new ingredient.">F. This involved selecting a new ingredient.</option></select></span></span></p>
<p>Product production</p>
<p><span class="ielts-listening-question-item"><span class="ielts-inline-select-wrap"><strong class="ielts-q-badge">30</strong><select data-qnum="30" name="question_30" class="ielts-inline-select"><option value="">[ 30 ] Tanlang...</option><option value="A. This was challenging but enjoyable.">A. This was challenging but enjoyable.</option><option value="B. This led to some disagreement.">B. This led to some disagreement.</option><option value="C. This was easy to decide on.">C. This was easy to decide on.</option><option value="D. This was helped by the guidelines provided.">D. This was helped by the guidelines provided.</option><option value="E. This seemed like an unnecessary stage.">E. This seemed like an unnecessary stage.</option><option value="F. This involved selecting a new ingredient.">F. This involved selecting a new ingredient.</option></select></span></span></p>
</div>                                                <div class="options-dnd-panel dnd-panel dnd-panel--inline" data-dnd-group="3178426">
                                                    <div class="dnd-panel-instruction">Drag and drop an option to fill in each blank.</div>
                                                    <div class="dnd-cards-container">
                                                                                                                    <div class="dnd-card" draggable="true" data-value="A" data-text="A. This was challenging but enjoyable.">
                                                                <span class="dnd-label">A.</span>
                                                                <span class="dnd-text">This was challenging but enjoyable.</span>
                                                            </div>
                                                                                                                    <div class="dnd-card" draggable="true" data-value="B" data-text="B. This led to some disagreement.">
                                                                <span class="dnd-label">B.</span>
                                                                <span class="dnd-text">This led to some disagreement.</span>
                                                            </div>
                                                                                                                    <div class="dnd-card" draggable="true" data-value="C" data-text="C. This was easy to decide on.">
                                                                <span class="dnd-label">C.</span>
                                                                <span class="dnd-text">This was easy to decide on.</span>
                                                            </div>
                                                                                                                    <div class="dnd-card" draggable="true" data-value="D" data-text="D. This was helped by the guidelines provided.">
                                                                <span class="dnd-label">D.</span>
                                                                <span class="dnd-text">This was helped by the guidelines provided.</span>
                                                            </div>
                                                                                                                    <div class="dnd-card" draggable="true" data-value="E" data-text="E. This seemed like an unnecessary stage.">
                                                                <span class="dnd-label">E.</span>
                                                                <span class="dnd-text">This seemed like an unnecessary stage.</span>
                                                            </div>
                                                                                                                    <div class="dnd-card" draggable="true" data-value="F" data-text="F. This involved selecting a new ingredient.">
                                                                <span class="dnd-label">F.</span>
                                                                <span class="dnd-text">This involved selecting a new ingredient.</span>
                                                            </div>
                                                                                                            </div>
                                                </div>
                                                                                    </div>
                                        <div class="ielts-reading-questions">
                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                        </div>
</div>', 'https://ielts-listening-audio.engnovatemedia.com/3178716-cambridge-ielts-21-academic-listening-test-2-3.mp3', 'TUTOR: Thanks for coming along, Nadia and Fergus. So this is a chance for you to give us some feedback about different aspects of your course. What would you like to begin with?
NADIA: I''ve enjoyed the sessions on food safety. There was some information there that I found really surprising, although some was stuff I knew already, like the rise in rates of obesity.
FERGUS: Yeah, that''s been in the news a lot. But I hadn''t realised that unsafe food causes more than 200 different diseases.
NADIA: No, I''d no idea it was that many. And speaking of diseases, I knew resistance to antibiotics is on the increase, but I didn''t know why ...
FERGUS: ...that it''s partly because when animals are treated with antibiotics then consumed by humans, the antibiotics get into the food chain. I had no idea about that either.
NADIA: Then the sessions provided a lot of information about plastic pollution from food packaging in the ocean, but I think that most of us were already aware of that.
FERGUS: Yeah. But I thought we could have done more on how much food is thrown away unnecessarily through fear of it being out of date, that was only mentioned in passing.
TUTOR: OK, I''ll bear that in mind. What did you think about the sessions from visiting lecturers, Fergus?
FERGUS: For me the most interesting one was about that project to prevent companies giving incorrect information to consumers about food.
TUTOR: Ah, food fraud, yes.
FERGUS: I thought it was really good to address a problem that''s faced by so many different groups - people with special religious rules, as well as vegetarians and vegans.
NADIA: And those with allergies.
FERGUS: Yeah. And another thing, we''ve had effective ways of analysing DNA for some time now and these can easily be applied to analysing food. But what the researchers succeeded in doing was to ensure that these tests were carried out at different stages in the food''s journey from the producer to the consumer. So they knew that the food actually came from the place it was supposed to, and had the ingredients it was meant to.
NADIA: Exactly. So customers can be confident about what they buy.
FERGUS: And the researchers had a good system for publicising their findings too.
NADIA: Well, I thought there were some problems with that, actually.
TUTOR: OK. And do you have any recommendations for new topics that we could include in the course?
NADIA: Well, I''m interested in how crop yields can be increased without damaging the environment.
FERGUS: But we''ve already done quite a bit on that - but not so much on the seafood industry, where stocks are in danger of being overexploited as a food source unless we can find ways of keeping stocks up.
NADIA: Yes, that''d be a good topic. And I''m interested in the idea of a personalised approach to diet, now we have the technology to analyse exactly what individuals need.
FERGUS: That sounds more like a medical topic than food science.
NADIA: OK. What about sessions on the variety of food and eating habits around the world? That''s very relevant nowadays.
FERGUS: Yes, I think the whole class would be interested in that.
NADIA: Then there''s technological stuff, things like 3D printing of food and smart packaging.
FERGUS: Mmm - maybe too specialist.
TUTOR: Now, I''m particularly interested in your project - the one where you developed a new food product. So talk me through the stages... first you had to decide on your initial aim.
FERGUS: We decided we wanted to create something people could eat on the go rather than in a restaurant.
NADIA: Yeah so we chose falafel, which was originally a Middle Eastern snack.
FERGUS: We made up our minds about that pretty quickly. I know some students found it a lot harder to choose, and wasted a lot of time.
NADIA: Then we had to do the literature review. We hadn''t done one of these before so, the handout with advice for the project was very useful here.
FERGUS: Yes, especially the advice on how to present the information. Then product development, actually deciding what we''d use to make the falafel, and for me the interesting thing about that was that we wanted it to be something a bit different from an ordinary falafel.
NADIA: We really made the right choice when we finally decided to use jackfruit, even though it wasn''t something that either of us had ever tasted before.
FERGUS: Yeah, like the name tells you, it''s a fruit but actually it''s really good in savoury dishes. The product production, working out how to make the falafel, was harder than I expected because I''d never made them before.
NADIA: It was mostly trial and error. We started off with the basic recipe and then experimented and when it went wrong...
FERGUS: ...which it did a lot of the time...
NADIA: ...we just moved on and kept adapting it and in the end it turned out fine and we had a lot of fun.
FERGUS: We did!
TUTOR: Thank you. Well, your project was a very good ....', 3)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, instructions = EXCLUDED.instructions, audio_url = EXCLUDED.audio_url, passage_text = EXCLUDED.passage_text;

INSERT INTO questions (id, section_id, question_type, question_text, options, correct_answer, points, order_index) VALUES
(210221, 21023, 'multiple_choice', 'Question 21', '["A", "B", "C", "D", "E"]'::jsonb, 'B / E', 1, 21),
(210222, 21023, 'multiple_choice', 'Question 22', '["A", "B", "C", "D", "E"]'::jsonb, 'B / E', 1, 22),
(210223, 21023, 'multiple_choice', 'Question 23', '["A", "B", "C", "D", "E"]'::jsonb, 'C / D', 1, 23),
(210224, 21023, 'multiple_choice', 'Question 24', '["A", "B", "C", "D", "E"]'::jsonb, 'C / D', 1, 24),
(210225, 21023, 'multiple_choice', 'Question 25', '["A", "B", "C", "D", "E"]'::jsonb, 'A / C', 1, 25),
(210226, 21023, 'multiple_choice', 'Question 26', '["A", "B", "C", "D", "E"]'::jsonb, 'A / C', 1, 26),
(210227, 21023, 'multiple_choice', 'Question 27', '["A", "B", "C", "D", "E"]'::jsonb, 'C', 1, 27),
(210228, 21023, 'multiple_choice', 'Question 28', '["A", "B", "C", "D", "E"]'::jsonb, 'D', 1, 28),
(210229, 21023, 'multiple_choice', 'Question 29', '["A", "B", "C", "D", "E"]'::jsonb, 'F', 1, 29),
(210230, 21023, 'multiple_choice', 'Question 30', '["A", "B", "C", "D", "E"]'::jsonb, 'A', 1, 30)
ON CONFLICT (id) DO UPDATE SET question_text = EXCLUDED.question_text, options = EXCLUDED.options, correct_answer = EXCLUDED.correct_answer, points = EXCLUDED.points;

INSERT INTO sections (id, test_id, type, title, instructions, audio_url, passage_text, order_index) VALUES
(21024, 2102, 'listening', 'Listening Part 4', '<div class="ielts-reading-container">
<h2 class="ielts-reading-question-section-heading">
                                            Questions 31-40                                                                                                                                                
                                                                                                                                    </h2>
                                                                                <div class="ielts-reading-question-section-content">
                                            <div class="ielts-listening-section-content-wrapper"><p>Complete the notes below.</p>
<p>Write ONE WORD ONLY for each answer.</p>
<p>Challenges facing the cruise ship industry</p>
<p>Problems with overtourism</p>
<p>• <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">31</strong><input type="text" data-qnum="31" name="question_31" class="ielts-inline-input" placeholder="[31] javob..." autocomplete="off" spellcheck="false"></span></span> is one of the worst problems.</p>
<p>• A tourist <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">32</strong><input type="text" data-qnum="32" name="question_32" class="ielts-inline-input" placeholder="[32] javob..." autocomplete="off" spellcheck="false"></span></span> is being introduced in some cities to reduce numbers, e.g. Barcelona.</p>
<p>• Bruges: action was taken to limit day trips from the nearby port because the city was becoming a ''theme park'' (e.g. many shops were only stocking <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">33</strong><input type="text" data-qnum="33" name="question_33" class="ielts-inline-input" placeholder="[33] javob..." autocomplete="off" spellcheck="false"></span></span> and souvenirs).</p>
<p>• Dubrovnik: limits the number of tourists by managing the <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">34</strong><input type="text" data-qnum="34" name="question_34" class="ielts-inline-input" placeholder="[34] javob..." autocomplete="off" spellcheck="false"></span></span> of cruise ship arrivals.</p>
<p>Problems of perception</p>
<p>• Cruises are generally associated with the elderly.</p>
<p>• There is an assumption about the <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">35</strong><input type="text" data-qnum="35" name="question_35" class="ielts-inline-input" placeholder="[35] javob..." autocomplete="off" spellcheck="false"></span></span> of cruises.</p>
<p>• People think there may be too many <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">36</strong><input type="text" data-qnum="36" name="question_36" class="ielts-inline-input" placeholder="[36] javob..." autocomplete="off" spellcheck="false"></span></span>.</p>
<p>Solutions</p>
<p>Cruise lines are attracting younger customers by:</p>
<p>• becoming more sustainable e.g. using hybrid engines.</p>
<p>• having a wide range of activities e.g. boxing, <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">37</strong><input type="text" data-qnum="37" name="question_37" class="ielts-inline-input" placeholder="[37] javob..." autocomplete="off" spellcheck="false"></span></span> and well-being programmes.</p>
<p>• offering a diverse selection of food including <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">38</strong><input type="text" data-qnum="38" name="question_38" class="ielts-inline-input" placeholder="[38] javob..." autocomplete="off" spellcheck="false"></span></span> options.</p>
<p>• providing reliable <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">39</strong><input type="text" data-qnum="39" name="question_39" class="ielts-inline-input" placeholder="[39] javob..." autocomplete="off" spellcheck="false"></span></span>.</p>
<p>• improving marketing on social media with high quality <span class="ielts-reading-question-item"><span class="ielts-inline-input-wrap"><strong class="ielts-q-badge">40</strong><input type="text" data-qnum="40" name="question_40" class="ielts-inline-input" placeholder="[40] javob..." autocomplete="off" spellcheck="false"></span></span>.</p>
</div>                                        </div>
                                        <div class="ielts-reading-questions">
                                                                                                                                                                                            </div>
                                        </div>                                                                    </div>
</div>', 'https://ielts-listening-audio.engnovatemedia.com/3178715-cambridge-ielts-21-academic-listening-test-2-4.mp3', 'For my presentation today I''m going to talk about some of the issues facing the cruise ship industry and then some ways these can be addressed. The cruise ship industry has partly been responsible for the effects of overtourism in recent decades. Overtourism occurs in places where excessive numbers of tourists cause significant problems. Pollution, for example, is among the greatest threats to many popular tourist destinations.
Of course, for many places it''s a difficult balance to achieve. They want to promote their city or island as a desirable tourist destination, but at the same time, are unable to cope with thousands of cruise ship passengers on a daily basis. The trouble is, excessive tourism is destroying the beauty spots and places of interest that people come to visit. Several cities, such as Barcelona, have responded by imposing a tax which all visitors to the city from cruise ships have to pay. But as it''s only a couple of euros, many green campaigners think it won''t deter enough people to make any difference.
Bruges is another city which became impossible to navigate at times because of the huge numbers of cruise passengers arriving on day trips from the port of Zeebrugge. The city was becoming like a ''theme park'', with shops only catering for tourists, selling chocolate, which Belgium is famous for, and other souvenirs. The local council took action to limit cruise passengers to a more manageable level.
Dubrovnik had to limit the numbers of cruise ships after it became extremely popular as a cruise ship destination when it featured in a hugely successful TV series. What it does now is control the timing of all cruise ship entries to the city''s port. However, many people feel this measure does not go far enough.
Cruise ships may be unpopular in some of their destinations but they also have an image problem. They''ve always been perceived as a safe holiday for the elderly, with not much on offer for families or young couples. A recent survey showed that cost is also a major factor in putting younger groups off going on a cruise. But what they don''t realise is that compared to other types of package holidays, cruises can actually be good value, as all activities and drinks are often included. And another perception is that cruises have lots of rules about what to wear and how to behave. But these days, most cruises are no longer very formal and behind the times.
So what solutions are there for cruise lines to overcome some of these problems? How can they appeal to younger customers? Well one selling point is that cruise ships are becoming more sustainable. New ships are built with hybrid engines with large batteries which means ships do not have to keep their engines running while docked.
Cruise lines are also designing ships specially for those in the age range of 21 to 45. The décor in these feels contemporary and there are a range of activities on board that you wouldn''t find on a more traditional cruise. There''s even a boxing ring on one ship, and most offer diving expeditions. But there''s also a huge focus on well-being with a variety of sessions of different kinds.
Food is always a very important part of any cruise and cruise ships have had to radically update their menus to suit the tastes of their younger customers. Vegan dishes are standard, for example. The restaurants on board have also gone paperless with menus available on screen.
Unlike older generations who went on cruises largely to get away from everything, younger people expect to be able to keep in touch with friends and family. Many people going on longer cruises also spend time working, so companies have to guarantee wifi that can be relied upon at all times.
My grandparents used to love looking through cruise brochures, even when they weren''t planning on going on a cruise. Until very recently TV ads for cruises always felt dated and aimed at retirees. Cruise lines have been slow to adopt the power of social media but that''s all changing. Leading cruise lines now employ top agencies to produce first rate videos for social media channels.
It will be interesting to see whether ...', 4)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, instructions = EXCLUDED.instructions, audio_url = EXCLUDED.audio_url, passage_text = EXCLUDED.passage_text;

INSERT INTO questions (id, section_id, question_type, question_text, options, correct_answer, points, order_index) VALUES
(210231, 21024, 'text_input', 'Challenges facing the cruise ship industry 
 Problems with overtourism 
 •  <strong', '[]'::jsonb, 'Pollution', 1, 31),
(210232, 21024, 'text_input', '• A tourist  <strong', '[]'::jsonb, 'tax', 1, 32),
(210233, 21024, 'text_input', 'many shops were only stocking  <strong', '[]'::jsonb, 'chocolate', 1, 33),
(210234, 21024, 'text_input', '• Dubrovnik: limits the number of tourists by managing the  <strong', '[]'::jsonb, 'timing', 1, 34),
(210235, 21024, 'text_input', '• There is an assumption about the  <strong', '[]'::jsonb, 'cost', 1, 35),
(210236, 21024, 'text_input', '• People think there may be too many  <strong', '[]'::jsonb, 'rules', 1, 36),
(210237, 21024, 'text_input', 'boxing,  <strong', '[]'::jsonb, 'diving', 1, 37),
(210238, 21024, 'text_input', '• offering a diverse selection of food including  <strong', '[]'::jsonb, 'vegan', 1, 38),
(210239, 21024, 'text_input', '• providing reliable  <strong', '[]'::jsonb, 'wifi / wi-fi', 1, 39),
(210240, 21024, 'text_input', '• improving marketing on social media with high quality  <strong', '[]'::jsonb, 'videos', 1, 40)
ON CONFLICT (id) DO UPDATE SET question_text = EXCLUDED.question_text, options = EXCLUDED.options, correct_answer = EXCLUDED.correct_answer, points = EXCLUDED.points;
